version: "3"
services:
  spark-master:
    build: .
    hostname: "spark-master"
    entrypoint: "/bin/bash master.sh"
    ports:
      - 8080:8080
      - 7077:7077
  spark-worker-a:
    build: .
    entrypoint: "/bin/bash worker.sh"
  spark-worker-b:
    build: .
    entrypoint: "/bin/bash worker.sh"
